services:
  postgres:
    image: postgres:16
    container_name: url-shortener-db

    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: url_shortener
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "5432:5432"