spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/url_shortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: UTC

  jwt:
    secret: ${JWT_SECRET:my-default-secret-key-my-default-secret-key}
    expiration: 3600000

  flyway:
    enabled: true