spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/url_shortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: UTC

  jwt:
    secret: ${JWT_SECRET:test-secret-key-test-secret-key-123456}
    expiration: 3600000

  flyway:
    enabled: true

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}